# Generated by Django 4.0.3 on 2022-03-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadcsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('CGst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('SGst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('IGst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Per', models.CharField(blank=True, max_length=30, null=True)),
                ('Rate', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
